// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WePromoLink.Data;

#nullable disable

namespace WePromoLink.Shared.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WePromoLink.HitModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Commission")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Counter")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FirstHitAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("GeoDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("GeolocatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsGeolocated")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastHitAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LinkModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Origin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Payed")
                        .HasColumnType("bit");

                    b.Property<string>("SubscriptionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GeoDataId");

                    b.HasIndex("LinkModelId");

                    b.ToTable("Hits");
                });

            modelBuilder.Entity("WePromoLink.Models.AbuseReportModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("UserId");

                    b.ToTable("AbuseReports");
                });

            modelBuilder.Entity("WePromoLink.Models.AffiliatedUserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberPayments")
                        .HasColumnType("int");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalPayments")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("UserModelId");

                    b.ToTable("AffiliatedUsers");
                });

            modelBuilder.Entity("WePromoLink.Models.AffiliateModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("AffiliateLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Affiliates")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("MRR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OTR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Profit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserModelId")
                        .IsUnique();

                    b.ToTable("AffiliatePrograms");
                });

            modelBuilder.Entity("WePromoLink.Models.BitcoinBillingMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UserModelId")
                        .IsUnique();

                    b.ToTable("BitcoinBillings");
                });

            modelBuilder.Entity("WePromoLink.Models.CampaignModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Budget")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EPM")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("ImageDataModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastClick")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastShared")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId");

                    b.HasIndex("ImageDataModelId");

                    b.HasIndex("UserModelId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("WePromoLink.Models.GenericEventModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GenericEvent");
                });

            modelBuilder.Entity("WePromoLink.Models.GeoDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Continent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryFlagUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(20, 14)
                        .HasColumnType("decimal(20,14)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(20, 14)
                        .HasColumnType("decimal(20,14)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GeoDatas");
                });

            modelBuilder.Entity("WePromoLink.Models.ImageDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Bound")
                        .HasColumnType("bit");

                    b.Property<string>("Compressed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CompressedAspectRatio")
                        .HasColumnType("float");

                    b.Property<int>("CompressedHeight")
                        .HasColumnType("int");

                    b.Property<int>("CompressedWidth")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Medium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MediumAspectRatio")
                        .HasColumnType("float");

                    b.Property<int>("MediumHeight")
                        .HasColumnType("int");

                    b.Property<int>("MediumWidth")
                        .HasColumnType("int");

                    b.Property<string>("Original")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OriginalAspectRatio")
                        .HasColumnType("float");

                    b.Property<int>("OriginalHeight")
                        .HasColumnType("int");

                    b.Property<int>("OriginalWidth")
                        .HasColumnType("int");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ThumbnailAspectRatio")
                        .HasColumnType("float");

                    b.Property<int>("ThumbnailHeight")
                        .HasColumnType("int");

                    b.Property<int>("ThumbnailWidth")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ImageDatas");
                });

            modelBuilder.Entity("WePromoLink.Models.JoinWaitingListModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JoinWaitingLists");
                });

            modelBuilder.Entity("WePromoLink.Models.LinkModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampaignModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("LastClick")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CampaignModelId");

                    b.HasIndex("ExternalId");

                    b.HasIndex("UserModelId");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("WePromoLink.Models.MyPageModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CallOfAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Conversion")
                        .HasColumnType("int");

                    b.Property<string>("ImageHeaderUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QRUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Template")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Visited")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserModelId")
                        .IsUnique();

                    b.ToTable("MyPages");
                });

            modelBuilder.Entity("WePromoLink.Models.NotificationModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Etag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId");

                    b.HasIndex("UserModelId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("WePromoLink.Models.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal?>("AmountNet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("CampaignModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("LinkModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PaymentProcessorFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeTranferId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CampaignModelId");

                    b.HasIndex("ExternalId");

                    b.HasIndex("LinkModelId");

                    b.HasIndex("UserModelId");

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("WePromoLink.Models.PrivacyModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("PublicMyPage")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowAffiliateLinkOnMyPage")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowAffiliateLinkOnProfile")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowCallOfActionOnMyPage")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowCampaignsOnProfile")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowEmailOnProfile")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowLinksOnMyPage")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowLinksOnProfile")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowProfitOnProfile")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowQRUrlOnProfile")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowSocialsOnMyPage")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowSocialsOnProfile")
                        .HasColumnType("bit");

                    b.Property<bool>("UseMyPageTemplate")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserModelId")
                        .IsUnique();

                    b.ToTable("Privacies");
                });

            modelBuilder.Entity("WePromoLink.Models.ProfileModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageHeaderUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MyPageId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Social")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserModelId")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("WePromoLink.Models.SettingModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CampaignClickedOnEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("CampaignClickedOnNotification")
                        .HasColumnType("bit");

                    b.Property<bool>("CampaignClickedOnRealTime")
                        .HasColumnType("bit");

                    b.Property<bool>("CampaignCreatedOnEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("CampaignCreatedOnNotification")
                        .HasColumnType("bit");

                    b.Property<bool>("CampaignCreatedOnRealTime")
                        .HasColumnType("bit");

                    b.Property<bool>("CampaignDeletedOnEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("CampaignDeletedOnNotification")
                        .HasColumnType("bit");

                    b.Property<bool>("CampaignDeletedOnRealTime")
                        .HasColumnType("bit");

                    b.Property<bool>("CampaignEditedOnEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("CampaignEditedOnNotification")
                        .HasColumnType("bit");

                    b.Property<bool>("CampaignEditedOnRealTime")
                        .HasColumnType("bit");

                    b.Property<string>("CampaignLanguages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CampaignPublishedOnEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("CampaignPublishedOnNotification")
                        .HasColumnType("bit");

                    b.Property<bool>("CampaignPublishedOnRealTime")
                        .HasColumnType("bit");

                    b.Property<bool>("CampaignSharedOnEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("CampaignSharedOnNotification")
                        .HasColumnType("bit");

                    b.Property<bool>("CampaignSharedOnRealTime")
                        .HasColumnType("bit");

                    b.Property<bool>("CampaignSoldOutOnEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("CampaignSoldOutOnNotification")
                        .HasColumnType("bit");

                    b.Property<bool>("CampaignSoldOutOnRealTime")
                        .HasColumnType("bit");

                    b.Property<bool>("CampaignUnPublishedOnEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("CampaignUnPublishedOnNotification")
                        .HasColumnType("bit");

                    b.Property<bool>("CampaignUnPublishedOnRealTime")
                        .HasColumnType("bit");

                    b.Property<bool>("HitGeoLocalizedSuccessOnEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("HitGeoLocalizedSuccessOnNotification")
                        .HasColumnType("bit");

                    b.Property<bool>("HitGeoLocalizedSuccessOnRealTime")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LinkClickedOnEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("LinkClickedOnNotification")
                        .HasColumnType("bit");

                    b.Property<bool>("LinkClickedOnRealTime")
                        .HasColumnType("bit");

                    b.Property<bool>("LinkCreatedOnEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("LinkCreatedOnNotification")
                        .HasColumnType("bit");

                    b.Property<bool>("LinkCreatedOnRealTime")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserModelId")
                        .IsUnique();

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("WePromoLink.Models.StaticPageDataTemplateModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Etag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("MaxAge")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StaticPageDataTemplates");
                });

            modelBuilder.Entity("WePromoLink.Models.StaticPageModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Etag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("MaxAge")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StaticPageDataTemplateModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StaticPageWebsiteTemplateModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StaticPageDataTemplateModelId");

                    b.HasIndex("StaticPageWebsiteTemplateModelId");

                    b.ToTable("StaticPages");
                });

            modelBuilder.Entity("WePromoLink.Models.StaticPageProductByPageModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AffiliateClicks")
                        .HasColumnType("int");

                    b.Property<int>("BuyClicks")
                        .HasColumnType("int");

                    b.Property<decimal>("Profit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("StaticPageModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StaticPageProductModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StaticPageModelId");

                    b.HasIndex("StaticPageProductModelId");

                    b.ToTable("StaticPageProductByPages");
                });

            modelBuilder.Entity("WePromoLink.Models.StaticPageProductByResourceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StaticPageProductModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StaticPageResourceModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StaticPageProductModelId");

                    b.HasIndex("StaticPageResourceModelId");

                    b.ToTable("StaticPageProductByResources");
                });

            modelBuilder.Entity("WePromoLink.Models.StaticPageProductModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AffiliateLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AffiliateProgram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Commission")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Inventory")
                        .HasColumnType("int");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("StaticPageProducts");
                });

            modelBuilder.Entity("WePromoLink.Models.StaticPageResourceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SizeMB")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StaticPageResources");
                });

            modelBuilder.Entity("WePromoLink.Models.StaticPageWebsiteTemplateModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Etag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("MaxAge")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StaticPageWebsiteTemplates");
                });

            modelBuilder.Entity("WePromoLink.Models.StripeBillingMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UserModelId")
                        .IsUnique();

                    b.ToTable("StripeBillings");
                });

            modelBuilder.Entity("WePromoLink.Models.SubscriptionFeatureModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("BoolValue")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("SubscriptionPlanModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionPlanModelId");

                    b.ToTable("SubscriptionFeatures");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e36dc510-e30b-4b3b-bd56-d9df6bf5a49f"),
                            BoolValue = false,
                            Name = "Campaigns",
                            Order = 1,
                            SubscriptionPlanModelId = new Guid("51daa39e-0e84-4d94-a770-b769463850a8"),
                            Value = "Unlimited"
                        },
                        new
                        {
                            Id = new Guid("00c9aeda-0782-4d05-bd88-6ef9d12cca8a"),
                            BoolValue = false,
                            Name = "Links",
                            Order = 2,
                            SubscriptionPlanModelId = new Guid("51daa39e-0e84-4d94-a770-b769463850a8"),
                            Value = "Unlimited"
                        },
                        new
                        {
                            Id = new Guid("0708ecc6-a8e7-4fd4-912b-dd48a8c20574"),
                            BoolValue = false,
                            Name = "Deposit fee",
                            Order = 4,
                            SubscriptionPlanModelId = new Guid("51daa39e-0e84-4d94-a770-b769463850a8"),
                            Value = "10%"
                        },
                        new
                        {
                            Id = new Guid("aa4946d6-4547-414a-9b39-f104a4181fb8"),
                            BoolValue = true,
                            Name = "Withdraw fee",
                            Order = 5,
                            SubscriptionPlanModelId = new Guid("51daa39e-0e84-4d94-a770-b769463850a8"),
                            Value = "10%"
                        },
                        new
                        {
                            Id = new Guid("af6ca5f3-deaa-422d-af72-fd2467166569"),
                            BoolValue = true,
                            Name = "Stripe Account",
                            Order = 3,
                            SubscriptionPlanModelId = new Guid("51daa39e-0e84-4d94-a770-b769463850a8"),
                            Value = "Standard"
                        },
                        new
                        {
                            Id = new Guid("a758b320-74b4-4f95-87d1-b9c88aa88fc3"),
                            BoolValue = false,
                            Name = "Campaigns",
                            Order = 1,
                            SubscriptionPlanModelId = new Guid("251343f4-52e2-45f6-b30f-f24a8c49741e"),
                            Value = "Unlimited"
                        },
                        new
                        {
                            Id = new Guid("0ecf7d20-ef7c-40da-b144-f26d71b60a78"),
                            BoolValue = false,
                            Name = "Links",
                            Order = 2,
                            SubscriptionPlanModelId = new Guid("251343f4-52e2-45f6-b30f-f24a8c49741e"),
                            Value = "Unlimited"
                        },
                        new
                        {
                            Id = new Guid("dcadc223-3611-4a85-b4fa-f22dd299b385"),
                            BoolValue = false,
                            Name = "Deposit fee",
                            Order = 4,
                            SubscriptionPlanModelId = new Guid("251343f4-52e2-45f6-b30f-f24a8c49741e"),
                            Value = "0%"
                        },
                        new
                        {
                            Id = new Guid("f417261e-ae11-40ae-84ff-9e9c2dda01d1"),
                            BoolValue = false,
                            Name = "Withdraw fee",
                            Order = 5,
                            SubscriptionPlanModelId = new Guid("251343f4-52e2-45f6-b30f-f24a8c49741e"),
                            Value = "0%"
                        },
                        new
                        {
                            Id = new Guid("22b8e6cb-55dc-4932-98d3-37c6ffdb1ebc"),
                            BoolValue = false,
                            Name = "Stripe Account",
                            Order = 3,
                            SubscriptionPlanModelId = new Guid("251343f4-52e2-45f6-b30f-f24a8c49741e"),
                            Value = "Express"
                        });
                });

            modelBuilder.Entity("WePromoLink.Models.SubscriptionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastPayment")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NextPayment")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SubscriptionPlanModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId");

                    b.HasIndex("SubscriptionPlanModelId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("WePromoLink.Models.SubscriptionPlanModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<decimal>("Annually")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("AnnualyPriceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Commission")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DepositFeePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<decimal>("Discount")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Monthly")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("MonthlyPriceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Upgradeable")
                        .HasColumnType("bit");

                    b.Property<decimal>("WithdrawFeePercent")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId");

                    b.ToTable("SubscriptionPlans");

                    b.HasData(
                        new
                        {
                            Id = new Guid("51daa39e-0e84-4d94-a770-b769463850a8"),
                            Active = true,
                            Annually = 0m,
                            AnnualyPriceId = "",
                            Commission = 0m,
                            DepositFeePercent = 10m,
                            Disabled = false,
                            Discount = 0m,
                            ExternalId = "x2Cc9RQucEzF",
                            Level = 1,
                            Monthly = 0m,
                            MonthlyPriceId = "",
                            Order = 2,
                            PaymentMethod = "stripe",
                            Tag = "",
                            Title = "Basic",
                            Upgradeable = false,
                            WithdrawFeePercent = 10m
                        },
                        new
                        {
                            Id = new Guid("251343f4-52e2-45f6-b30f-f24a8c49741e"),
                            Active = true,
                            Annually = 891m,
                            AnnualyPriceId = "price_1OsdMCC26XBdqsojOddpYcZQ",
                            Commission = 0m,
                            DepositFeePercent = 0m,
                            Disabled = false,
                            Discount = 25m,
                            ExternalId = "EIAvzngmir3W",
                            Level = 2,
                            Monthly = 99m,
                            MonthlyPriceId = "price_1OsdMCC26XBdqsojSdyEGOUY",
                            Order = 3,
                            PaymentMethod = "stripe",
                            Tag = "Popular",
                            Title = "Professional",
                            Upgradeable = false,
                            WithdrawFeePercent = 0m
                        });
                });

            modelBuilder.Entity("WePromoLink.Models.SurveyAnswerModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SurveyQuestionModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SurveyQuestionModelId");

                    b.ToTable("SurveyAnswers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0a0b9c44-d4b9-4575-a8a6-23070ba6d519"),
                            SurveyQuestionModelId = new Guid("527355e6-b2dd-4948-978d-cd27ca2f8e6a"),
                            Value = "Earning money through affiliate marketing"
                        },
                        new
                        {
                            Id = new Guid("bb88a70b-d2be-41f1-a653-3d6a89890466"),
                            SurveyQuestionModelId = new Guid("527355e6-b2dd-4948-978d-cd27ca2f8e6a"),
                            Value = "Promoting my products or services"
                        },
                        new
                        {
                            Id = new Guid("6c69816d-b809-49c4-8cd0-e61f2cb45496"),
                            SurveyQuestionModelId = new Guid("527355e6-b2dd-4948-978d-cd27ca2f8e6a"),
                            Value = "Exploring new advertising opportunities"
                        },
                        new
                        {
                            Id = new Guid("f6482cc9-1485-44fb-bee9-1304daf07d68"),
                            SurveyQuestionModelId = new Guid("527355e6-b2dd-4948-978d-cd27ca2f8e6a"),
                            Value = "Connecting with other users and businesses"
                        },
                        new
                        {
                            Id = new Guid("c78c8031-5b76-42d4-9604-becc575085c4"),
                            SurveyQuestionModelId = new Guid("481e23cc-274b-4e77-a615-4e7fe9cbb065"),
                            Value = "Credit/Debit card"
                        },
                        new
                        {
                            Id = new Guid("56818da3-c514-405c-98ba-16bc021662eb"),
                            SurveyQuestionModelId = new Guid("481e23cc-274b-4e77-a615-4e7fe9cbb065"),
                            Value = "PayPal"
                        },
                        new
                        {
                            Id = new Guid("8398cc5b-6bfb-482a-9837-3685bda7a9de"),
                            SurveyQuestionModelId = new Guid("481e23cc-274b-4e77-a615-4e7fe9cbb065"),
                            Value = "Stripe"
                        },
                        new
                        {
                            Id = new Guid("ceb885db-0f1c-455a-b616-d17ebc18b70f"),
                            SurveyQuestionModelId = new Guid("481e23cc-274b-4e77-a615-4e7fe9cbb065"),
                            Value = "Bank transfer"
                        },
                        new
                        {
                            Id = new Guid("c65b3ca9-eaad-45ce-8d6c-636d8fb5ad48"),
                            SurveyQuestionModelId = new Guid("b9537c05-0004-4063-852e-90de39f90c6e"),
                            Value = "Monthly subscription fee"
                        },
                        new
                        {
                            Id = new Guid("f2495822-6154-4099-a41a-d2ab9eeb9501"),
                            SurveyQuestionModelId = new Guid("b9537c05-0004-4063-852e-90de39f90c6e"),
                            Value = "Commission on earnings"
                        },
                        new
                        {
                            Id = new Guid("7b79f529-f5fc-425e-816f-7586928b6936"),
                            SurveyQuestionModelId = new Guid("b9537c05-0004-4063-852e-90de39f90c6e"),
                            Value = "I'm not sure"
                        },
                        new
                        {
                            Id = new Guid("6c8b8778-b109-4ec1-b4df-89b198cee430"),
                            SurveyQuestionModelId = new Guid("53b02b05-e776-430a-9c3a-d2b7664eb13e"),
                            Value = "Extremely useful"
                        },
                        new
                        {
                            Id = new Guid("39f8b69d-9724-43ef-bef9-6761710263e2"),
                            SurveyQuestionModelId = new Guid("53b02b05-e776-430a-9c3a-d2b7664eb13e"),
                            Value = "Very useful"
                        },
                        new
                        {
                            Id = new Guid("c4abbe42-b81e-4814-9760-1b2aeeb86401"),
                            SurveyQuestionModelId = new Guid("53b02b05-e776-430a-9c3a-d2b7664eb13e"),
                            Value = "Somewhat useful"
                        },
                        new
                        {
                            Id = new Guid("0c2b7934-ad7a-4fc7-bfeb-a6391ce00f71"),
                            SurveyQuestionModelId = new Guid("53b02b05-e776-430a-9c3a-d2b7664eb13e"),
                            Value = "Not very useful"
                        },
                        new
                        {
                            Id = new Guid("414c8646-14f1-4644-bab1-30adc65d9b55"),
                            SurveyQuestionModelId = new Guid("53b02b05-e776-430a-9c3a-d2b7664eb13e"),
                            Value = "Not useful at all"
                        },
                        new
                        {
                            Id = new Guid("ca42c8fe-3c21-47a9-a070-0cba26382a36"),
                            SurveyQuestionModelId = new Guid("a746e9b7-1205-417f-b52d-11c06237abad"),
                            Value = "More campaign customization options"
                        },
                        new
                        {
                            Id = new Guid("04c6ad19-1e4f-4c94-9866-bc7232900a3f"),
                            SurveyQuestionModelId = new Guid("a746e9b7-1205-417f-b52d-11c06237abad"),
                            Value = "Advanced analytics and reporting"
                        },
                        new
                        {
                            Id = new Guid("7d39037c-d5b7-4422-bf5e-cf89e09b7aaf"),
                            SurveyQuestionModelId = new Guid("a746e9b7-1205-417f-b52d-11c06237abad"),
                            Value = "Integration with other advertising platforms"
                        },
                        new
                        {
                            Id = new Guid("48fca2f4-cd5c-41d4-bbe4-b0a1b5861287"),
                            SurveyQuestionModelId = new Guid("a746e9b7-1205-417f-b52d-11c06237abad"),
                            Value = "Improved user interface and navigation"
                        },
                        new
                        {
                            Id = new Guid("bac2f4e7-d8b2-4ff0-a7f9-3569d3341497"),
                            SurveyQuestionModelId = new Guid("a746e9b7-1205-417f-b52d-11c06237abad"),
                            Value = "I'm not sure"
                        });
                });

            modelBuilder.Entity("WePromoLink.Models.SurveyDatapointModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SurveyAnswerModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SurveyQuestionModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SurveyAnswerModelId");

                    b.HasIndex("SurveyQuestionModelId");

                    b.ToTable("SurveyDatapoints");
                });

            modelBuilder.Entity("WePromoLink.Models.SurveyQuestionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Group")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SurveyQuestions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("527355e6-b2dd-4948-978d-cd27ca2f8e6a"),
                            Group = 1,
                            Value = "What motivates you to use a platform like WePromoLink?"
                        },
                        new
                        {
                            Id = new Guid("481e23cc-274b-4e77-a615-4e7fe9cbb065"),
                            Group = 2,
                            Value = "Which payment methods do you prefer for platform subscriptions and earnings withdrawals?"
                        },
                        new
                        {
                            Id = new Guid("b9537c05-0004-4063-852e-90de39f90c6e"),
                            Group = 3,
                            Value = "Do you prefer a monthly subscription fee or paying a commission on earnings?"
                        },
                        new
                        {
                            Id = new Guid("53b02b05-e776-430a-9c3a-d2b7664eb13e"),
                            Group = 4,
                            Value = "How useful do you find the WePromoLink platform for your advertising needs?"
                        },
                        new
                        {
                            Id = new Guid("a746e9b7-1205-417f-b52d-11c06237abad"),
                            Group = 5,
                            Value = "What additional features or improvements would you like to see on the WePromoLink platform?"
                        });
                });

            modelBuilder.Entity("WePromoLink.Models.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Available")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BlockageCause")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirebaseId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSubscribed")
                        .HasColumnType("bit");

                    b.Property<decimal>("Profit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SubscriptionModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ThumbnailImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId");

                    b.HasIndex("SubscriptionModelId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WePromoLink.HitModel", b =>
                {
                    b.HasOne("WePromoLink.Models.GeoDataModel", "GeoData")
                        .WithMany()
                        .HasForeignKey("GeoDataId");

                    b.HasOne("WePromoLink.Models.LinkModel", "Link")
                        .WithMany("Hits")
                        .HasForeignKey("LinkModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeoData");

                    b.Navigation("Link");
                });

            modelBuilder.Entity("WePromoLink.Models.AbuseReportModel", b =>
                {
                    b.HasOne("WePromoLink.Models.CampaignModel", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId");

                    b.HasOne("WePromoLink.Models.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WePromoLink.Models.AffiliatedUserModel", b =>
                {
                    b.HasOne("WePromoLink.Models.UserModel", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WePromoLink.Models.UserModel", "User")
                        .WithMany("AffiliatedUsers")
                        .HasForeignKey("UserModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WePromoLink.Models.AffiliateModel", b =>
                {
                    b.HasOne("WePromoLink.Models.UserModel", "UserModel")
                        .WithOne("AffiliateProgram")
                        .HasForeignKey("WePromoLink.Models.AffiliateModel", "UserModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserModel");
                });

            modelBuilder.Entity("WePromoLink.Models.BitcoinBillingMethod", b =>
                {
                    b.HasOne("WePromoLink.Models.UserModel", "User")
                        .WithOne("BitcoinBillingMethod")
                        .HasForeignKey("WePromoLink.Models.BitcoinBillingMethod", "UserModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WePromoLink.Models.CampaignModel", b =>
                {
                    b.HasOne("WePromoLink.Models.ImageDataModel", "ImageData")
                        .WithMany()
                        .HasForeignKey("ImageDataModelId");

                    b.HasOne("WePromoLink.Models.UserModel", "User")
                        .WithMany("Campaigns")
                        .HasForeignKey("UserModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImageData");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WePromoLink.Models.LinkModel", b =>
                {
                    b.HasOne("WePromoLink.Models.CampaignModel", "Campaign")
                        .WithMany("Links")
                        .HasForeignKey("CampaignModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WePromoLink.Models.UserModel", "User")
                        .WithMany("Links")
                        .HasForeignKey("UserModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WePromoLink.Models.MyPageModel", b =>
                {
                    b.HasOne("WePromoLink.Models.UserModel", "UserModel")
                        .WithOne("MyPage")
                        .HasForeignKey("WePromoLink.Models.MyPageModel", "UserModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserModel");
                });

            modelBuilder.Entity("WePromoLink.Models.NotificationModel", b =>
                {
                    b.HasOne("WePromoLink.Models.UserModel", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WePromoLink.Models.PaymentTransaction", b =>
                {
                    b.HasOne("WePromoLink.Models.CampaignModel", "Campaign")
                        .WithMany("Transactions")
                        .HasForeignKey("CampaignModelId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("WePromoLink.Models.LinkModel", "Link")
                        .WithMany("Transactions")
                        .HasForeignKey("LinkModelId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("WePromoLink.Models.UserModel", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserModelId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Campaign");

                    b.Navigation("Link");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WePromoLink.Models.PrivacyModel", b =>
                {
                    b.HasOne("WePromoLink.Models.UserModel", "UserModel")
                        .WithOne("Privacy")
                        .HasForeignKey("WePromoLink.Models.PrivacyModel", "UserModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserModel");
                });

            modelBuilder.Entity("WePromoLink.Models.ProfileModel", b =>
                {
                    b.HasOne("WePromoLink.Models.UserModel", "UserModel")
                        .WithOne("Profile")
                        .HasForeignKey("WePromoLink.Models.ProfileModel", "UserModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserModel");
                });

            modelBuilder.Entity("WePromoLink.Models.SettingModel", b =>
                {
                    b.HasOne("WePromoLink.Models.UserModel", "UserModel")
                        .WithOne("Setting")
                        .HasForeignKey("WePromoLink.Models.SettingModel", "UserModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserModel");
                });

            modelBuilder.Entity("WePromoLink.Models.StaticPageModel", b =>
                {
                    b.HasOne("WePromoLink.Models.StaticPageDataTemplateModel", "StaticPageDataTemplate")
                        .WithMany()
                        .HasForeignKey("StaticPageDataTemplateModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WePromoLink.Models.StaticPageWebsiteTemplateModel", "StaticPageWebsiteTemplate")
                        .WithMany()
                        .HasForeignKey("StaticPageWebsiteTemplateModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StaticPageDataTemplate");

                    b.Navigation("StaticPageWebsiteTemplate");
                });

            modelBuilder.Entity("WePromoLink.Models.StaticPageProductByPageModel", b =>
                {
                    b.HasOne("WePromoLink.Models.StaticPageModel", "Page")
                        .WithMany()
                        .HasForeignKey("StaticPageModelId");

                    b.HasOne("WePromoLink.Models.StaticPageProductModel", "Product")
                        .WithMany()
                        .HasForeignKey("StaticPageProductModelId");

                    b.Navigation("Page");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WePromoLink.Models.StaticPageProductByResourceModel", b =>
                {
                    b.HasOne("WePromoLink.Models.StaticPageProductModel", "Product")
                        .WithMany()
                        .HasForeignKey("StaticPageProductModelId");

                    b.HasOne("WePromoLink.Models.StaticPageResourceModel", "Resource")
                        .WithMany()
                        .HasForeignKey("StaticPageResourceModelId");

                    b.Navigation("Product");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("WePromoLink.Models.StripeBillingMethod", b =>
                {
                    b.HasOne("WePromoLink.Models.UserModel", "User")
                        .WithOne("StripeBillingMethod")
                        .HasForeignKey("WePromoLink.Models.StripeBillingMethod", "UserModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WePromoLink.Models.SubscriptionFeatureModel", b =>
                {
                    b.HasOne("WePromoLink.Models.SubscriptionPlanModel", null)
                        .WithMany("Features")
                        .HasForeignKey("SubscriptionPlanModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WePromoLink.Models.SubscriptionModel", b =>
                {
                    b.HasOne("WePromoLink.Models.SubscriptionPlanModel", "SubscriptionPlan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("SubscriptionPlanModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("WePromoLink.Models.SurveyAnswerModel", b =>
                {
                    b.HasOne("WePromoLink.Models.SurveyQuestionModel", "SurveyQuestionModel")
                        .WithMany("Answers")
                        .HasForeignKey("SurveyQuestionModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SurveyQuestionModel");
                });

            modelBuilder.Entity("WePromoLink.Models.SurveyDatapointModel", b =>
                {
                    b.HasOne("WePromoLink.Models.SurveyAnswerModel", "SurveyAnswerModel")
                        .WithMany("Datapoints")
                        .HasForeignKey("SurveyAnswerModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WePromoLink.Models.SurveyQuestionModel", "SurveyQuestionModel")
                        .WithMany("Datapoints")
                        .HasForeignKey("SurveyQuestionModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SurveyAnswerModel");

                    b.Navigation("SurveyQuestionModel");
                });

            modelBuilder.Entity("WePromoLink.Models.UserModel", b =>
                {
                    b.HasOne("WePromoLink.Models.SubscriptionModel", "Subscription")
                        .WithOne("User")
                        .HasForeignKey("WePromoLink.Models.UserModel", "SubscriptionModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("WePromoLink.Models.CampaignModel", b =>
                {
                    b.Navigation("Links");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("WePromoLink.Models.LinkModel", b =>
                {
                    b.Navigation("Hits");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("WePromoLink.Models.SubscriptionModel", b =>
                {
                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("WePromoLink.Models.SubscriptionPlanModel", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("WePromoLink.Models.SurveyAnswerModel", b =>
                {
                    b.Navigation("Datapoints");
                });

            modelBuilder.Entity("WePromoLink.Models.SurveyQuestionModel", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Datapoints");
                });

            modelBuilder.Entity("WePromoLink.Models.UserModel", b =>
                {
                    b.Navigation("AffiliateProgram")
                        .IsRequired();

                    b.Navigation("AffiliatedUsers");

                    b.Navigation("BitcoinBillingMethod")
                        .IsRequired();

                    b.Navigation("Campaigns");

                    b.Navigation("Links");

                    b.Navigation("MyPage")
                        .IsRequired();

                    b.Navigation("Notifications");

                    b.Navigation("Privacy")
                        .IsRequired();

                    b.Navigation("Profile")
                        .IsRequired();

                    b.Navigation("Setting")
                        .IsRequired();

                    b.Navigation("StripeBillingMethod")
                        .IsRequired();

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
