apiVersion: v1
kind: Pod
metadata:
  name: web-app-pod
spec:
  containers:
    - name: web-app-container
      image: cod4it/web.wepromolink:1.0
      ports:
        - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app-container
          image: cod4it/web.wepromolink:1.0
          ports:
            - containerPort: 80
      imagePullSecrets:  # Referencia al Secret creado para las credenciales de DockerHub
        - name: dockerhub-credentials

---
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Cambia esto según el tipo de servicio que desees
