name: CI

on: [push]

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV01_IP }}
          username: ${{ secrets.DEV01_USERNAME }}
          password: ${{ secrets.DEV01_PASS }}
          script: cd wepromolink && cd api.wepromolink && docker-compose down && git pull && docker build . -t cod4it/wepromolink:1.0 && docker push cod4it/wepromolink:1.0 && docker-compose up --build --force-recreate --no-deps -d
