name: WepromoLink API Pipeline
on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Get wepromolink tag
        run: echo "WEPROMOLINK_TAG=$(cat wepromolink.txt)" >> $GITHUB_ENV
        
      - name: Get hit worker tag
        run: echo "HITWORKER_TAG=$(cat hitworker.txt)" >> $GITHUB_ENV
        
      - name: Get stripe worker tag
        run: echo "STRIPEWORKER_TAG=$(cat stripeworker.txt)" >> $GITHUB_ENV

      - name: Get stats worker tag
        run: echo "STATSWORKER_TAG=$(cat statworker.txt)" >> $GITHUB_ENV

      - name: Get controller tag
        run: echo "CONTROLLER_TAG=$(cat controller.txt)" >> $GITHUB_ENV
        
      - name: Build and Push Docker Image WePromolink
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: cod4it/wepromolink:${{ env.WEPROMOLINK_TAG }}
          file: WePromoLink.Dockerfile
          
      - name: Build and Push Docker Image WePromolink.HitWorker
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: cod4it/wepromolink.hitworker:${{ env.HITWORKER_TAG }}
          file: WePromoLink.HitWorker.Dockerfile
          
      - name: Build and Push Docker Image WePromolink.StripeWorker
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: cod4it/wepromolink.stripeworker:${{ env.STRIPEWORKER_TAG }}
          file: WePromoLink.StripeWorker.Dockerfile

      - name: Build and Push Docker Image WePromolink.StatsWorker
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: cod4it/wepromolink.statsworker:${{ env.STATSWORKER_TAG }}
          file: WePromoLink.StatsWorker.Dockerfile

      - name: Build and Push Docker Image WePromolink.Controller
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: cod4it/wepromolink.controller:${{ env.CONTROLLER_TAG }}
          file: WePromoLink.Controller.Dockerfile
  
