name: WepromoLink API Pipeline
on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Get current tag
        run: echo "IMAGE_TAG=$(cat tag.txt)" >> $GITHUB_ENV
        
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: cod4it/wepromolink:${{ env.IMAGE_TAG }}
          dockerfile: WePromoLink.Dockerfile
  
